name: build and push

on:
  workflow_dispatch:
  push:
    branch:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
      users: actions/checkout@v4
  
