name: build and tag

on:
  pull_request:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '**/.dockerignore'
      - .github/**
      - '**.go'
      - '**.mod'
      - '**.sum'
      - config/**
      - '**/Makefile*'
      - '**/documentation.md'
      - .golangci.yaml
      - .goreleaser.yaml

  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
