name: build and tag

on:
  workflow_dispatch:
  pull_request:
    branch:
      - master
  push:
    master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
